import { parseCollection } from './bgg'
import { BoardGame } from './types'
import { DEEDEEN_COLLECTION } from './deedeen-collection'

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

// Custom error so callers can distinguish "not found" from other failures
export class CollectionError extends Error {
  status: number
  constructor(message: string, status: number) {
    super(message)
    this.name = 'CollectionError'
    this.status = status
  }
}

// Demo data for testing UI when BGG API is unavailable
const DEMO_DATA: BoardGame[] = [
  {
    id: '13',
    name: 'Catan',
    yearPublished: 1995,
    thumbnail: 'https://cf.geekdo-images.com/small/img/dn9kkG91fTk_W7zrDLHkO_I4KYc=/fit-in/200x150/pic1077128.jpg',
    image: 'https://cf.geekdo-images.com/large/img/1234/pic1077128.jpg',
    minPlayers: 3,
    maxPlayers: 4,
    minPlayTime: 60,
    maxPlayTime: 90,
    userRating: 8.5,
    communityRating: 7.2,
    bggRank: 241,
    numPlays: 12,
  },
  {
    id: '175914',
    name: 'Gloomhaven',
    yearPublished: 2017,
    thumbnail: 'https://cf.geekdo-images.com/small/img/1_OERnj7q0glb2pCqNNQx6JxAMfrM=/fit-in/200x150/pic2272277.jpg',
    image: 'https://cf.geekdo-images.com/large/img/1_OERnj7q0glb2pCqNNQx6JxAMfrM=/fit-in/500x500/pic2272277.jpg',
    minPlayers: 1,
    maxPlayers: 4,
    minPlayTime: 60,
    maxPlayTime: 120,
    userRating: 9,
    communityRating: 8.8,
    bggRank: 4,
    numPlays: 25,
  },
  {
    id: '224517',
    name: 'Brass: Birmingham',
    yearPublished: 2018,
    thumbnail: 'https://cf.geekdo-images.com/small/img/tKJT3gJQ9HBWo2o6uPi6Wx2JFZo=/fit-in/200x150/pic3627169.jpg',
    image: 'https://cf.geekdo-images.com/large/img/tKJT3gJQ9HBWo2o6uPi6Wx2JFZo=/fit-in/500x500/pic3627169.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    minPlayTime: 60,
    maxPlayTime: 120,
    userRating: 8.8,
    communityRating: 8.6,
    bggRank: 2,
    numPlays: 8,
  },
]

/**
 * Fetches and parses a BGG collection directly (no internal HTTP round-trip).
 * Handles BGG's 202 "processing" responses with retries, and falls back to
 * demo data for the "demo"/"deedeen" usernames when BGG requires auth.
 */
export async function getCollectionData(
  username: string,
  maxAttempts: number = 5,
  delayMs: number = 3000
): Promise<BoardGame[]> {
  // Real scraped collection for Deedeen (BGG's XML API now requires auth)
  if (username.toLowerCase() === 'deedeen') {
    return DEEDEEN_COLLECTION
  }

  const isDemoUser = username.toLowerCase() === 'demo'

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    console.log(`[getCollectionData] Attempt ${attempt}/${maxAttempts} for "${username}"`)

    let response: Response
    try {
      response = await fetch(
        `https://boardgamegeek.com/xmlapi2/collection?username=${encodeURIComponent(username)}&stats=1&own=1`,
        { headers: { 'User-Agent': 'BoardGameCollectionViewer/1.0' } }
      )
    } catch (networkError) {
      console.error(`[getCollectionData] Network error on attempt ${attempt}:`, networkError)
      // Demo fallback when BGG is unreachable
      if (isDemoUser) return DEMO_DATA
      if (attempt === maxAttempts) {
        throw new CollectionError('Could not reach BoardGameGeek. Please try again later.', 503)
      }
      await sleep(delayMs)
      continue
    }

    console.log(`[getCollectionData] Status ${response.status}`)

    if (response.status === 200) {
      const xml = await response.text()
      return parseCollection(xml)
    }

    if (response.status === 202) {
      // Collection is being generated by BGG — wait and retry
      if (attempt < maxAttempts) {
        await sleep(delayMs)
        continue
      }
      // Demo fallback if BGG keeps stalling
      if (isDemoUser) return DEMO_DATA
      throw new CollectionError('BoardGameGeek is still preparing this collection. Please try again.', 503)
    }

    if (response.status === 404) {
      throw new CollectionError('User not found or collection is private', 404)
    }

    if (response.status === 401 || response.status === 403) {
      // BGG now sometimes requires auth — serve demo data for known test users
      if (isDemoUser) {
        console.warn('[getCollectionData] BGG requires auth; returning demo data')
        return DEMO_DATA
      }
      throw new CollectionError('BoardGameGeek currently requires authentication for this collection.', 502)
    }

    // Any other status
    if (isDemoUser) return DEMO_DATA
    throw new CollectionError(`BoardGameGeek API error (status ${response.status}).`, 502)
  }

  if (isDemoUser) return DEMO_DATA
  throw new CollectionError('Failed to fetch collection after multiple attempts.', 503)
}
