import { CommunityGame } from './types'

// Real Barudak Board Game Club collection — auto-generated by scripts/scrape-community.mjs
// 109 games owned across 16 members.
// Generated by scripts/scrape-community.mjs — do not edit by hand.

export const MEMBERS: string[] = ["Andrea","Aswin","Billy","Daniel","Dedi","Dzikri","Lavin","Malik","Noah","Poetra","Reinard","Sam","Wicak","Winoko","Yofiandhy","Yos"]

export const COMMUNITY_GAMES: CommunityGame[] = [
  {
    "id": "370391",
    "name": "12 Rivers",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/jQPUh_KhKor6oTLyzRg7iA__original/img/9bFRQP6bwJIy3O2SWlTAGFWE3Xc=/0x0/filters:format(jpeg)/pic7077087.jpg",
    "thumbnail": "https://cf.geekdo-images.com/jQPUh_KhKor6oTLyzRg7iA__previewthumb/img/l96SZdY8taY0O9nABUBHJOfZgtg=/fit-in/300x320/filters:strip_icc()/pic7077087.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 75,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy"
    ],
    "owners": [
      "Noah"
    ]
  },
  {
    "id": "371947",
    "name": "3 Ring Circus",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/rlVMW44IxSdXg0mfbdOdOg__original/img/0dv_H-9NXnu7aKwbZD0T9cHTHyw=/0x0/filters:format(jpeg)/pic7819093.jpg",
    "thumbnail": "https://cf.geekdo-images.com/rlVMW44IxSdXg0mfbdOdOg__previewthumb/img/37iY5MhbfYdeLzytKP05TQmK-Qs=/fit-in/300x320/filters:strip_icc()/pic7819093.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 75,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "332312",
    "name": "5-Minute Dungeon: Big Box",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/FHL2iLvpZVolI7BXGA9O0A__original/img/qI4v8ak05pGEwnyxYaJw2OsgG_k=/0x0/filters:format(png)/pic8559204.png",
    "thumbnail": "https://cf.geekdo-images.com/FHL2iLvpZVolI7BXGA9O0A__previewthumb/img/guZycQDhFYpa96QX7lyj7PfvtYw=/fit-in/300x320/filters:strip_icc()/pic8559204.png",
    "minPlayers": 2,
    "maxPlayers": 6,
    "minPlayTime": 5,
    "maxPlayTime": 30,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Fantasy",
      "Real-time"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "294514",
    "name": "5-Minute Mystery",
    "yearPublished": 2020,
    "image": "https://cf.geekdo-images.com/227j91odzi4v2S2pbxcscg__original/img/OJ-arew7SLsyDboqb7J9p6--cB0=/0x0/filters:format(jpeg)/pic7486281.jpg",
    "thumbnail": "https://cf.geekdo-images.com/227j91odzi4v2S2pbxcscg__previewthumb/img/kNdrr98fSelfCBSUYwmVN3KskiM=/fit-in/300x320/filters:strip_icc()/pic7486281.jpg",
    "minPlayers": 1,
    "maxPlayers": 6,
    "minPlayTime": 5,
    "maxPlayTime": 30,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Murder/Mystery",
      "Party Game"
    ],
    "owners": [
      "Noah"
    ]
  },
  {
    "id": "192458",
    "name": "51st State: Master Set",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/oaDIooAl30NgVUWeIpC1sg__original/img/7jICcOLqm0LTdlXVUOUJloyqj2A=/0x0/filters:format(jpeg)/pic2945432.jpg",
    "thumbnail": "https://cf.geekdo-images.com/oaDIooAl30NgVUWeIpC1sg__previewthumb/img/h-a3ZpyvEjt-cBX7gF2aygwAOhU=/fit-in/300x320/filters:strip_icc()/pic2945432.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 90,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "City Building",
      "Economic",
      "Science Fiction"
    ],
    "owners": [
      "Yos"
    ]
  },
  {
    "id": "432",
    "name": "6 nimmt!",
    "yearPublished": 1994,
    "image": "https://cf.geekdo-images.com/WuOY1XAIJQ-RGAmT_apW_w__original/img/06TSBC2s-cwbxfPmy_pf7n5p-jM=/0x0/filters:format(jpeg)/pic8632998.jpg",
    "thumbnail": "https://cf.geekdo-images.com/WuOY1XAIJQ-RGAmT_apW_w__previewthumb/img/WVHvt65NbYpXOPXj3u-l-44fbR0=/fit-in/300x320/filters:strip_icc()/pic8632998.jpg",
    "minPlayers": 2,
    "maxPlayers": 10,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Number"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "177736",
    "name": "A Feast for Odin",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/s9oGMCo1fcfV4Dk3EnqLZw__original/img/N1X-0JB1GapFVhl98nP4tNFXMcM=/0x0/filters:format(png)/pic3146943.png",
    "thumbnail": "https://cf.geekdo-images.com/s9oGMCo1fcfV4Dk3EnqLZw__previewthumb/img/VbIzyHZo-Cs0C_N-0GZpcMwz1Xw=/fit-in/300x320/filters:strip_icc()/pic3146943.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 120,
    "communityRating": 8.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Farming",
      "Industry / Manufacturing",
      "Medieval",
      "Puzzle"
    ],
    "owners": [
      "Aswin"
    ]
  },
  {
    "id": "205610",
    "name": "A Game of Thrones: Hand of the King",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/eKmDyXnsFmnzF5cuv32hjA__original/img/KfNO0NfiugWpxMnoruB2Z1W2w-g=/0x0/filters:format(jpeg)/pic3122395.jpg",
    "thumbnail": "https://cf.geekdo-images.com/eKmDyXnsFmnzF5cuv32hjA__previewthumb/img/pml95LjDjiUIWSqE5YYTyAvyMDU=/fit-in/300x320/filters:strip_icc()/pic3122395.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 30,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Card Game",
      "Fantasy"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "334011",
    "name": "A Gentle Rain",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/EqqXUmjIuGspHNwt1UnDEQ__original/img/zROVukvZZ-GZR2Rm8JfzLOzGKnE=/0x0/filters:format(png)/pic7769466.png",
    "thumbnail": "https://cf.geekdo-images.com/EqqXUmjIuGspHNwt1UnDEQ__previewthumb/img/ctziCPYs7qbZSUJdrqU6rTtPdZM=/fit-in/300x320/filters:strip_icc()/pic7769466.png",
    "minPlayers": 1,
    "maxPlayers": 1,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Puzzle"
    ],
    "owners": [
      "Dedi"
    ]
  },
  {
    "id": "41636",
    "name": "Abandon Ship",
    "yearPublished": 2008,
    "image": "https://cf.geekdo-images.com/falWKQYiaakhMEUczzGsKA__original/img/LLQRSdD51bDxCVQRVjGXhLl8epU=/0x0/filters:format(jpeg)/pic527382.jpg",
    "thumbnail": "https://cf.geekdo-images.com/falWKQYiaakhMEUczzGsKA__previewthumb/img/hmhZcP1yiP-lO64DSveVHHACzzI=/fit-in/300x320/filters:strip_icc()/pic527382.jpg",
    "minPlayers": 3,
    "maxPlayers": 7,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 6.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Bluffing",
      "Nautical"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "237898",
    "name": "Acaraki: The Java Herbalist",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/2shgGiJkIMn4tL8nCs_sGg__original/img/j1Fm6kvkUmjVA84hTK5Nr8CUlAY=/0x0/filters:format(jpeg)/pic3834510.jpg",
    "thumbnail": "https://cf.geekdo-images.com/2shgGiJkIMn4tL8nCs_sGg__previewthumb/img/M7Ljj_NyifFBfcSqINu2zq2K15s=/fit-in/300x320/filters:strip_icc()/pic3834510.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 60,
    "communityRating": 6.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Fantasy",
      "Medical"
    ],
    "owners": [
      "Noah"
    ]
  },
  {
    "id": "5",
    "name": "Acquire",
    "yearPublished": 1963,
    "image": "https://cf.geekdo-images.com/gIQlWhlaqjPiunZjjwz_XA__original/img/ZRnstiRspAWMorOn6UKoKx9ibwI=/0x0/filters:format(jpeg)/pic8483227.jpg",
    "thumbnail": "https://cf.geekdo-images.com/gIQlWhlaqjPiunZjjwz_XA__previewthumb/img/zPhpK9pZuxUQ469lxO88z81DJMI=/fit-in/300x320/filters:strip_icc()/pic8483227.jpg",
    "minPlayers": 2,
    "maxPlayers": 6,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Territory Building"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "266538",
    "name": "Aftershock: San Francisco & Venice",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/9s8F6dmfsyMK68o2aF26_g__original/img/RBdOfc5BtNDZA2A6XiTfb7u5mzU=/0x0/filters:format(jpeg)/pic4598862.jpg",
    "thumbnail": "https://cf.geekdo-images.com/9s8F6dmfsyMK68o2aF26_g__previewthumb/img/9E3ynqarzFGe9ck6T80lVX1zPxo=/fit-in/300x320/filters:strip_icc()/pic4598862.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 60,
    "maxPlayTime": 60,
    "communityRating": 6.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "City Building",
      "Civilization",
      "Negotiation"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "4098",
    "name": "Age of Steam: Deluxe Edition",
    "yearPublished": 2002,
    "image": "https://cf.geekdo-images.com/gBPzZsgm9nrUYVfdK216NA__original/img/eQEmKYEWVoNvEx6PZYZv13275io=/0x0/filters:format(png)/pic4557340.png",
    "thumbnail": "https://cf.geekdo-images.com/gBPzZsgm9nrUYVfdK216NA__previewthumb/img/BZjCiXjO2_qvqqF_LnLC570lIxo=/fit-in/300x320/filters:strip_icc()/pic4557340.png",
    "minPlayers": 1,
    "maxPlayers": 6,
    "minPlayTime": 120,
    "maxPlayTime": 120,
    "communityRating": 7.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Trains",
      "Transportation"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "315943",
    "name": "Agents of SMERSH: Epic Edition",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/uM36vkRwCaIUN1gCwCqe8w__original/img/UNNx24ifPHVKWlvj3yTaGnRxzgA=/0x0/filters:format(jpeg)/pic5570005.jpg",
    "thumbnail": "https://cf.geekdo-images.com/uM36vkRwCaIUN1gCwCqe8w__previewthumb/img/1qtQo8kUWmDmnJHcV9gRBPpE6yo=/fit-in/300x320/filters:strip_icc()/pic5570005.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 90,
    "maxPlayTime": 120,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Spies/Secret Agents",
      "Travel"
    ],
    "owners": [
      "Sam"
    ]
  },
  {
    "id": "31260",
    "name": "Agricola",
    "yearPublished": 2007,
    "image": "https://cf.geekdo-images.com/3L6ZtOll9W5O6-3-EwSMyw__original/img/V37KuMJlCzpxAilzN39BzeLvc9Q=/0x0/filters:format(jpeg)/pic1899157.jpg",
    "thumbnail": "https://cf.geekdo-images.com/3L6ZtOll9W5O6-3-EwSMyw__previewthumb/img/ivLnPAYxZuyiP1nQzAcgswPmocE=/fit-in/300x320/filters:strip_icc()/pic1899157.jpg",
    "minPlayers": 1,
    "maxPlayers": 5,
    "minPlayTime": 30,
    "maxPlayTime": 150,
    "communityRating": 7.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Economic",
      "Farming"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "359402",
    "name": "Ahoy",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/yHPkYCQixecmdL9Sabj6kQ__original/img/DxD2mODd6VeiC7nVTFUFL7URgtk=/0x0/filters:format(png)/pic6946121.png",
    "thumbnail": "https://cf.geekdo-images.com/yHPkYCQixecmdL9Sabj6kQ__previewthumb/img/sjiNNoBkujHrVgp_bj5Dh4xywrI=/fit-in/300x320/filters:strip_icc()/pic6946121.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 75,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Nautical",
      "Pirates"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "357563",
    "name": "Akropolis",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/OTb0hIJHE-U3eD0FmpBrzA__original/img/GpSyHl2wwgLJ6JHJAjPbEQk4MNU=/0x0/filters:format(jpeg)/pic6705097.jpg",
    "thumbnail": "https://cf.geekdo-images.com/OTb0hIJHE-U3eD0FmpBrzA__previewthumb/img/PP_p7Ue5yofKv-vWJ7imPAstp1k=/fit-in/300x320/filters:strip_icc()/pic6705097.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 20,
    "maxPlayTime": 30,
    "communityRating": 7.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "City Building",
      "Territory Building"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "492",
    "name": "Aladdin's Dragons",
    "yearPublished": 2000,
    "image": "https://cf.geekdo-images.com/GFgQQ4ZMH8kr3LsGvYHZHw__original/img/aGawfUSiBKA_0TuH0A2k-NaaoeE=/0x0/filters:format(jpeg)/pic143493.jpg",
    "thumbnail": "https://cf.geekdo-images.com/GFgQQ4ZMH8kr3LsGvYHZHw__previewthumb/img/34OslBp7vut9Lh6aLzask-Olm2k=/fit-in/300x320/filters:strip_icc()/pic143493.jpg",
    "minPlayers": 3,
    "maxPlayers": 5,
    "minPlayTime": 60,
    "maxPlayTime": 90,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Arabian",
      "Bluffing",
      "Fantasy",
      "Medieval"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "58886",
    "name": "Alba Longa",
    "yearPublished": 2011,
    "image": "https://cf.geekdo-images.com/p8_8_blmtmJIPKRBl9lOow__original/img/9SqlxoDpF72sHSSBCdRn2k2XeoU=/0x0/filters:format(jpeg)/pic1124914.jpg",
    "thumbnail": "https://cf.geekdo-images.com/p8_8_blmtmJIPKRBl9lOow__previewthumb/img/Q1J8yQzwf3JQ6Hr8W4LAO2Zamnk=/fit-in/300x320/filters:strip_icc()/pic1124914.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 6.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "City Building",
      "Civilization",
      "Economic"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "161970",
    "name": "Alchemists",
    "yearPublished": 2014,
    "image": "https://cf.geekdo-images.com/ztNshEv3Fsm46HCJaEOFPw__original/img/SP4ItZ27dLweUPbz_bF7C-P7GtA=/0x0/filters:format(png)/pic2241156.png",
    "thumbnail": "https://cf.geekdo-images.com/ztNshEv3Fsm46HCJaEOFPw__previewthumb/img/PQ7Ja1Z-2CWzk-jtUaDixyESWXs=/fit-in/300x320/filters:strip_icc()/pic2241156.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 120,
    "maxPlayTime": 120,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Deduction",
      "Fantasy"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "6249",
    "name": "Alhambra",
    "yearPublished": 2003,
    "image": "https://cf.geekdo-images.com/OiqKsYDh7pqeRYKG__kMSw__original/img/Oe2ZTGE2hUnyZQIEoIjM_zwYfcY=/0x0/filters:format(jpeg)/pic4893652.jpg",
    "thumbnail": "https://cf.geekdo-images.com/OiqKsYDh7pqeRYKG__kMSw__previewthumb/img/3yFe4Ra6lUMU19KBQ9qfNVLW_hE=/fit-in/300x320/filters:strip_icc()/pic4893652.jpg",
    "minPlayers": 2,
    "maxPlayers": 6,
    "minPlayTime": 45,
    "maxPlayTime": 60,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "City Building",
      "Medieval"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "48726",
    "name": "Alien Frontiers",
    "yearPublished": 2010,
    "image": "https://cf.geekdo-images.com/UWZTWLXFfg_6HpXJmviL3g__original/img/1EiMWmB4iGMDRbaXuvZQtlszM_Q=/0x0/filters:format(png)/pic3360924.png",
    "thumbnail": "https://cf.geekdo-images.com/UWZTWLXFfg_6HpXJmviL3g__previewthumb/img/5a4qmjij3S-NvG45HQ1S4f8QOX4=/fit-in/300x320/filters:strip_icc()/pic3360924.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Dice",
      "Science Fiction",
      "Space Exploration"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "278783",
    "name": "Almanac: The Dragon Road",
    "yearPublished": 2020,
    "image": "https://cf.geekdo-images.com/DNTBKaFRQ75DGOMkfXYUtw__original/img/F3ZUWcftNh26ymlyIp-75tvGydE=/0x0/filters:format(jpeg)/pic4708967.jpg",
    "thumbnail": "https://cf.geekdo-images.com/DNTBKaFRQ75DGOMkfXYUtw__previewthumb/img/q8jRfgFAVV9Ku_vnZjniLylM_ng=/fit-in/300x320/filters:strip_icc()/pic4708967.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 90,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "234487",
    "name": "Altiplano",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/hgUDu_oG0uhnOWX4WM2vXA__original/img/S0BVejCX4yDWZv934q6BS7gAF9M=/0x0/filters:format(jpeg)/pic4070329.jpg",
    "thumbnail": "https://cf.geekdo-images.com/hgUDu_oG0uhnOWX4WM2vXA__previewthumb/img/7_onTFYyqHUqAzv3kyhqviduKpk=/fit-in/300x320/filters:strip_icc()/pic4070329.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 7.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic"
    ],
    "owners": [
      "Daniel",
      "Winoko"
    ]
  },
  {
    "id": "260710",
    "name": "Amul",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/MUv5NahPYX16NbrFgmzg0A__original/img/0h1NPwx34VDezWBqpW4JBNbKHp4=/0x0/filters:format(jpeg)/pic4810206.jpg",
    "thumbnail": "https://cf.geekdo-images.com/MUv5NahPYX16NbrFgmzg0A__previewthumb/img/_JhJDYs2HGKTeroErFTiUcdIUQw=/fit-in/300x320/filters:strip_icc()/pic4810206.jpg",
    "minPlayers": 3,
    "maxPlayers": 8,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Arabian",
      "Card Game",
      "Medieval"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "5404",
    "name": "Amun-Re",
    "yearPublished": 2003,
    "image": "https://cf.geekdo-images.com/wFD0mXh1AZshtsYlrBXyzA__original/img/TbMBl_wTToaiNN9YIF4nixlM6SE=/0x0/filters:format(jpeg)/pic2748305.jpg",
    "thumbnail": "https://cf.geekdo-images.com/wFD0mXh1AZshtsYlrBXyzA__previewthumb/img/5moiZzeV-OLQn3unXlYIfKRLMFw=/fit-in/300x320/filters:strip_icc()/pic2748305.jpg",
    "minPlayers": 3,
    "maxPlayers": 5,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "Economic"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "185343",
    "name": "Anachrony",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/31quLNzteInnevVRAABoow__original/img/3KfMPSj7jjhG0g5lQBsO-bn67D0=/0x0/filters:format(jpeg)/pic3499707.jpg",
    "thumbnail": "https://cf.geekdo-images.com/31quLNzteInnevVRAABoow__previewthumb/img/67Ec04C7no6SAawuGONEdSwncEE=/fit-in/300x320/filters:strip_icc()/pic3499707.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 120,
    "communityRating": 8.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Science Fiction"
    ],
    "owners": [
      "Yos"
    ]
  },
  {
    "id": "338093",
    "name": "Ancient Knowledge",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/EDJ1Xynm6XjAKeG-q2B85A__original/img/fjmKvrqL1EfIvWltRy1vw49Jf58=/0x0/filters:format(jpeg)/pic7600216.jpg",
    "thumbnail": "https://cf.geekdo-images.com/EDJ1Xynm6XjAKeG-q2B85A__previewthumb/img/YeJl_cO8TVu2bsBMqY1805QWbCA=/fit-in/300x320/filters:strip_icc()/pic7600216.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 75,
    "maxPlayTime": 75,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "Card Game",
      "Civilization",
      "Mythology"
    ],
    "owners": [
      "Wicak"
    ]
  },
  {
    "id": "285967",
    "name": "Ankh: Gods of Egypt",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/_al0scMG_pQfGVM31Scf1Q__original/img/h4jBTaOjznJgWELa6tTrfPqqSeA=/0x0/filters:format(jpeg)/pic6107853.jpg",
    "thumbnail": "https://cf.geekdo-images.com/_al0scMG_pQfGVM31Scf1Q__previewthumb/img/r1ADKPGtE6t_eJOISr2rjKXYwIE=/fit-in/300x320/filters:strip_icc()/pic6107853.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 7.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "Fighting",
      "Miniatures",
      "Mythology"
    ],
    "owners": [
      "Poetra"
    ]
  },
  {
    "id": "322421",
    "name": "Aqua Garden",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/JyJ-FixOIyxKW0nEQMxNGw__original/img/g3nexrAoQtw66scTNtuJEHkla4c=/0x0/filters:format(png)/pic8927686.png",
    "thumbnail": "https://cf.geekdo-images.com/JyJ-FixOIyxKW0nEQMxNGw__previewthumb/img/G8xFtp03jeRXsA14qdg6T9-gASs=/fit-in/300x320/filters:strip_icc()/pic8927686.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 40,
    "maxPlayTime": 60,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Puzzle"
    ],
    "owners": [
      "Noah",
      "Winoko"
    ]
  },
  {
    "id": "159508",
    "name": "AquaSphere",
    "yearPublished": 2014,
    "image": "https://cf.geekdo-images.com/K7Hq_KDgr8jJHMtW21XcfQ__original/img/PckhyT2sfyT93TPkIRyKrvPpPMs=/0x0/filters:format(jpeg)/pic2197124.jpg",
    "thumbnail": "https://cf.geekdo-images.com/K7Hq_KDgr8jJHMtW21XcfQ__previewthumb/img/80kds4FON4RsZOfFHNSbvFii3MQ=/fit-in/300x320/filters:strip_icc()/pic2197124.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 100,
    "maxPlayTime": 100,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Nautical",
      "Science Fiction"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "360471",
    "name": "Aquamarine",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/Tz21bWwOaJcsgUCOeP5G_Q__original/img/McGiEvDXD952_Jf_BPGsaDBqmUQ=/0x0/filters:format(png)/pic6983965.png",
    "thumbnail": "https://cf.geekdo-images.com/Tz21bWwOaJcsgUCOeP5G_Q__previewthumb/img/rc40FZ7ClbkGZxYFpGShIOzaoq4=/fit-in/300x320/filters:strip_icc()/pic6983965.png",
    "minPlayers": 1,
    "maxPlayers": 100,
    "minPlayTime": 20,
    "maxPlayTime": 30,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Nautical",
      "Print & Play"
    ],
    "owners": [
      "Andrea",
      "Reinard"
    ]
  },
  {
    "id": "34194",
    "name": "Aquaretto",
    "yearPublished": 2008,
    "image": "https://cf.geekdo-images.com/Uy_XB4UjqR3iwouKDMqxNg__original/img/QUWCCAB_VW7-jiRVCKWDVBGkLIU=/0x0/filters:format(jpeg)/pic1603517.jpg",
    "thumbnail": "https://cf.geekdo-images.com/Uy_XB4UjqR3iwouKDMqxNg__previewthumb/img/3xG8T7dHoAflj4Ba1BzoVQdDHcg=/fit-in/300x320/filters:strip_icc()/pic1603517.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "371077",
    "name": "Arborea",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/KHT8Ex0wvRs5wAWPNo3xNg__original/img/iMUGBOw1H51W0thj6tgXMrnPf6Q=/0x0/filters:format(png)/pic7230067.png",
    "thumbnail": "https://cf.geekdo-images.com/KHT8Ex0wvRs5wAWPNo3xNg__previewthumb/img/o8oZewXGwF67RxTjo3YoOzZnA98=/fit-in/300x320/filters:strip_icc()/pic7230067.png",
    "minPlayers": 1,
    "maxPlayers": 5,
    "minPlayTime": 90,
    "maxPlayTime": 120,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Fantasy"
    ],
    "owners": [
      "Lavin"
    ]
  },
  {
    "id": "140934",
    "name": "Arboretum",
    "yearPublished": 2015,
    "image": "https://cf.geekdo-images.com/XYOn10oXBrDqHySf0jvnyQ__original/img/RMi0pEsP8agfH-tgYkeRGilD3oo=/0x0/filters:format(png)/pic4172124.png",
    "thumbnail": "https://cf.geekdo-images.com/XYOn10oXBrDqHySf0jvnyQ__previewthumb/img/HV9AxAEDpP6djHLrq7F0NYP3nxE=/fit-in/300x320/filters:strip_icc()/pic4172124.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Bluffing",
      "Card Game"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "259710",
    "name": "Arcane Alley",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/KIisJpF2cgm5Koxdbt7nMQ__original/img/ln1-OKAA8ofo2Fw23zkB8a8Nfuw=/0x0/filters:format(png)/pic4327749.png",
    "thumbnail": "https://cf.geekdo-images.com/KIisJpF2cgm5Koxdbt7nMQ__previewthumb/img/SHTDuBlbVtcfAMNR3hdr5_PRjK4=/fit-in/300x320/filters:strip_icc()/pic4327749.png",
    "minPlayers": 2,
    "maxPlayers": 6,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 7.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Andrea"
    ]
  },
  {
    "id": "191300",
    "name": "Archaeology: The New Expedition",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/5fsW7qzvnkg8L0iVx_AM1A__original/img/4EIwkLf_b6eVmziTozPeDKKOymc=/0x0/filters:format(png)/pic2805898.png",
    "thumbnail": "https://cf.geekdo-images.com/5fsW7qzvnkg8L0iVx_AM1A__previewthumb/img/Xbics-V9klKkPkrNN7sawD4R2gs=/fit-in/300x320/filters:strip_icc()/pic2805898.png",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 20,
    "maxPlayTime": 30,
    "communityRating": 7.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Billy"
    ]
  },
  {
    "id": "236457",
    "name": "Architects of the West Kingdom",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/OAX7HfOz-9N60StgADzd0g__original/img/x2Y_DYWrzzleMETfnu7Jm3R8jPo=/0x0/filters:format(png)/pic3781944.png",
    "thumbnail": "https://cf.geekdo-images.com/OAX7HfOz-9N60StgADzd0g__previewthumb/img/Yp-2A54e5l5tjNYQI6et0H6f9qY=/fit-in/300x320/filters:strip_icc()/pic3781944.png",
    "minPlayers": 1,
    "maxPlayers": 5,
    "minPlayTime": 60,
    "maxPlayTime": 80,
    "communityRating": 7.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "City Building",
      "Medieval"
    ],
    "owners": [
      "Lavin",
      "Winoko",
      "Reinard"
    ]
  },
  {
    "id": "56931",
    "name": "Arena: Roma II",
    "yearPublished": 2009,
    "image": "https://cf.geekdo-images.com/8znSQz4Tr83zzC8BzH8tsA__original/img/9HB5CpB_tuGIXzXwzTusPKHxWng=/0x0/filters:format(jpeg)/pic578807.jpg",
    "thumbnail": "https://cf.geekdo-images.com/8znSQz4Tr83zzC8BzH8tsA__previewthumb/img/qJ82qAo8FWTJI1Vrx_Q6DSmgKd0=/fit-in/300x320/filters:strip_icc()/pic578807.jpg",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "Card Game",
      "Dice"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "257499",
    "name": "Arkham Horror (Third Edition)",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/09KeqyJEtu2qcskbtlOhqw__original/img/H6qePV4xg2vrwXoWcOhAhIZUtSo=/0x0/filters:format(jpeg)/pic5726297.jpg",
    "thumbnail": "https://cf.geekdo-images.com/09KeqyJEtu2qcskbtlOhqw__previewthumb/img/rMwscU2jRoLvMUXD0SE7fMM05y8=/fit-in/300x320/filters:strip_icc()/pic5726297.jpg",
    "minPlayers": 1,
    "maxPlayers": 6,
    "minPlayTime": 120,
    "maxPlayTime": 180,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Fighting",
      "Horror",
      "Novel-based"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "205637",
    "name": "Arkham Horror: The Card Game",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/B5F5ulz0UivNgrI9Ky0euA__original/img/guEKCewM_2e5ugltSN3dTSwdZJI=/0x0/filters:format(jpeg)/pic3122349.jpg",
    "thumbnail": "https://cf.geekdo-images.com/B5F5ulz0UivNgrI9Ky0euA__previewthumb/img/pqrW_DRlQiztPg4Yu9_k4WFiuxk=/fit-in/300x320/filters:strip_icc()/pic3122349.jpg",
    "minPlayers": 1,
    "maxPlayers": 2,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 8.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Card Game",
      "Collectible Components",
      "Exploration",
      "Horror",
      "Novel-based"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "359609",
    "name": "Arkham Horror: The Card Game (Revised Edition)",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/RdCWCXPnBGSxoOhk5Hkq_g__original/img/ekoKDLjgeUoPw3mpPUPfy-Xnjeo=/0x0/filters:format(jpeg)/pic6530423.jpg",
    "thumbnail": "https://cf.geekdo-images.com/RdCWCXPnBGSxoOhk5Hkq_g__previewthumb/img/yRPkoOErSkt7uAUwGGj5HkKKIeY=/fit-in/300x320/filters:strip_icc()/pic6530423.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 180,
    "communityRating": 8.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Card Game",
      "Collectible Components",
      "Exploration",
      "Fantasy",
      "Horror",
      "Novel-based"
    ],
    "owners": [
      "Sam"
    ]
  },
  {
    "id": "300664",
    "name": "Arkwright: The Card Game",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/8idwh3TfQ5FWGaMExD5HRw__original/img/B1k6WF1u1t4JFMLfF4BgTsAlvuI=/0x0/filters:format(jpeg)/pic5408665.jpg",
    "thumbnail": "https://cf.geekdo-images.com/8idwh3TfQ5FWGaMExD5HRw__previewthumb/img/SuNbcrVYZ29wSnDJK6G94MwWpko=/fit-in/300x320/filters:strip_icc()/pic5408665.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 100,
    "communityRating": 7.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Industry / Manufacturing"
    ],
    "owners": [
      "Andrea"
    ]
  },
  {
    "id": "395375",
    "name": "Art Society",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/_-kTI7KnJp7PmbZ5ISS5RQ__original/img/zi_ULxc-unXwKj4zaXYA-MN-EO8=/0x0/filters:format(png)/pic7628025.png",
    "thumbnail": "https://cf.geekdo-images.com/_-kTI7KnJp7PmbZ5ISS5RQ__previewthumb/img/2IPIy58RRgmtDh04OqHdaItrgaE=/fit-in/300x320/filters:strip_icc()/pic7628025.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 60,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "72991",
    "name": "Asara",
    "yearPublished": 2010,
    "image": "https://cf.geekdo-images.com/kmvWFYCQNzjMjF3PhWzcLw__original/img/TX1Zo-SHRYSnCdm_88l-JsMcMwA=/0x0/filters:format(jpeg)/pic745896.jpg",
    "thumbnail": "https://cf.geekdo-images.com/kmvWFYCQNzjMjF3PhWzcLw__previewthumb/img/74xC4r2q-LMwqfn-vV0N_jOH35Y=/fit-in/300x320/filters:strip_icc()/pic745896.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 60,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy",
      "Medieval"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "304531",
    "name": "Ascension Tactics: Miniatures Deckbuilding Game",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/891ZOmibeW3iRhEcdN0B5w__original/img/KQojWcEDJSItT4irky_t5Ut8kNI=/0x0/filters:format(png)/pic7364675.png",
    "thumbnail": "https://cf.geekdo-images.com/891ZOmibeW3iRhEcdN0B5w__previewthumb/img/B0B6z5UZEkMLS3rmCx3P581SL_k=/fit-in/300x320/filters:strip_icc()/pic7364675.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 90,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy",
      "Miniatures"
    ],
    "owners": [
      "Malik"
    ]
  },
  {
    "id": "369270",
    "name": "Astra",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/Z56Asr5C-r750kPW6ZemMg__original/img/Xqrx-bBlzW7O5nS8kxzpJkvgOG0=/0x0/filters:format(jpeg)/pic7040562.jpg",
    "thumbnail": "https://cf.geekdo-images.com/Z56Asr5C-r750kPW6ZemMg__previewthumb/img/Z7clpWGO-u2W2np1gNGjui8r3qM=/fit-in/300x320/filters:strip_icc()/pic7040562.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 40,
    "maxPlayTime": 90,
    "communityRating": 0,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [],
    "owners": [
      "Noah"
    ]
  },
  {
    "id": "307844",
    "name": "Atheneum: Mystic Library",
    "yearPublished": 2020,
    "image": "https://cf.geekdo-images.com/sSsr77t1nTarmMTyokJerw__original/img/PCtprH2JcqekZeb6MjQDQPvZFfM=/0x0/filters:format(png)/pic5365420.png",
    "thumbnail": "https://cf.geekdo-images.com/sSsr77t1nTarmMTyokJerw__previewthumb/img/XyHSeQ0q7L1nDHGB4EPIhSWeh6k=/fit-in/300x320/filters:strip_icc()/pic5365420.png",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Fantasy",
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "362452",
    "name": "Atiwa",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/9S_Ci89ADHj7sZ4SwHY19w__original/img/pCu8znBZuPZBPcyCptTnUhbHNKg=/0x0/filters:format(jpeg)/pic7245009.jpg",
    "thumbnail": "https://cf.geekdo-images.com/9S_Ci89ADHj7sZ4SwHY19w__previewthumb/img/9GrdcaULB1R4NcFDIxGXoHxrcWQ=/fit-in/300x320/filters:strip_icc()/pic7245009.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 120,
    "communityRating": 7.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Economic",
      "Educational",
      "Environmental",
      "Farming",
      "Territory Building"
    ],
    "owners": [
      "Malik"
    ]
  },
  {
    "id": "383459",
    "name": "Aurum",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/1MRtI2kpEGUanQQ246p-nw__original/img/_kFH93aoMHDf8VXpDzfl3kBIW6E=/0x0/filters:format(jpeg)/pic7439092.jpg",
    "thumbnail": "https://cf.geekdo-images.com/1MRtI2kpEGUanQQ246p-nw__previewthumb/img/-ZThoezTFGAuxhjBgX2NyfQEF8w=/fit-in/300x320/filters:strip_icc()/pic7439092.jpg",
    "minPlayers": 3,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "390163",
    "name": "Avant Carde",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/56cj78lZ8qCxFxUqoit2Dw__original/img/VhOa6Ho0_KoK3IALsInXbXAYLJ0=/0x0/filters:format(jpeg)/pic7581598.jpg",
    "thumbnail": "https://cf.geekdo-images.com/56cj78lZ8qCxFxUqoit2Dw__previewthumb/img/ZeHsGU1jZZn5aaXXSVyr3E2mofo=/fit-in/300x320/filters:strip_icc()/pic7581598.jpg",
    "minPlayers": 1,
    "maxPlayers": 5,
    "minPlayTime": 25,
    "maxPlayTime": 35,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Number"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "188866",
    "name": "Awkward Guests: The Walton Case",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/Awopfw5_5Qyh-7YcSbtudA__original/img/GxYtTK43oCTDn2J3pyukUw07bKo=/0x0/filters:format(jpeg)/pic4870482.jpg",
    "thumbnail": "https://cf.geekdo-images.com/Awopfw5_5Qyh-7YcSbtudA__previewthumb/img/-mLTV2JET2RXlPwJpJNuK8u5ZPc=/fit-in/300x320/filters:strip_icc()/pic4870482.jpg",
    "minPlayers": 1,
    "maxPlayers": 8,
    "minPlayTime": 45,
    "maxPlayTime": 75,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Deduction",
      "Humor",
      "Movies / TV / Radio theme",
      "Murder/Mystery"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "230802",
    "name": "Azul",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/AkbtYVc6xXJF3c9EUrakklcclKw=/0x0/filters:format(png)/pic6973671.png",
    "thumbnail": "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__previewthumb/img/qLCJBbjkXD_hN7ftt-5DLpC1xTw=/fit-in/300x320/filters:strip_icc()/pic6973671.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle",
      "Renaissance"
    ],
    "owners": [
      "Yos",
      "Poetra",
      "Malik",
      "Dzikri",
      "Winoko",
      "Reinard"
    ]
  },
  {
    "id": "431038",
    "name": "Azul Duel",
    "yearPublished": 2025,
    "image": "https://cf.geekdo-images.com/wcYNm1g5mtv6LNZGok_PZw__original/img/wa_8MgicsqinY_mAAEbp5eld218=/0x0/filters:format(png)/pic8491761.png",
    "thumbnail": "https://cf.geekdo-images.com/wcYNm1g5mtv6LNZGok_PZw__previewthumb/img/9KT5vu6DKpTzSc14P8TNglO16lM=/fit-in/300x320/filters:strip_icc()/pic8491761.png",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "363247",
    "name": "Azul: Master Chocolatier",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/CHIy1KMWI-LCkiux4q81Fg__original/img/cWe3u0UaHUWOWmFRGFAQYlFuYW4=/0x0/filters:format(png)/pic6871709.png",
    "thumbnail": "https://cf.geekdo-images.com/CHIy1KMWI-LCkiux4q81Fg__previewthumb/img/ZAx4D7S1ZFI8drvhopuuk6t3klQ=/fit-in/300x320/filters:strip_icc()/pic6871709.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "346965",
    "name": "Azul: Queen's Garden",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/l-NBWJ1gIcfOCfrvAw8qvw__original/img/VaPUWBlEE3Wg_QGYAsHxKV8mBkw=/0x0/filters:format(jpeg)/pic6389125.jpg",
    "thumbnail": "https://cf.geekdo-images.com/l-NBWJ1gIcfOCfrvAw8qvw__previewthumb/img/1OEipv3hNE7PneaPyRKwmt4HTvw=/fit-in/300x320/filters:strip_icc()/pic6389125.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 60,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle",
      "Renaissance"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "256226",
    "name": "Azul: Stained Glass of Sintra",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/RrYR1xB8H7D1B5GwNV8jgQ__original/img/unI8OEWp9Fdv3D_dLahPPdLG1qc=/0x0/filters:format(jpeg)/pic4212417.jpg",
    "thumbnail": "https://cf.geekdo-images.com/RrYR1xB8H7D1B5GwNV8jgQ__previewthumb/img/eouSSCOPPfH9n6zULq4RJofJfkY=/fit-in/300x320/filters:strip_icc()/pic4212417.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle",
      "Renaissance"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "287954",
    "name": "Azul: Summer Pavilion",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/843kZ6WR0HfyXWEybA6L7A__original/img/VtYGvhy_YCSw14FpV8FGzv0eMe4=/0x0/filters:format(jpeg)/pic4930887.jpg",
    "thumbnail": "https://cf.geekdo-images.com/843kZ6WR0HfyXWEybA6L7A__previewthumb/img/kRzbeAmqfrI20-j4QTqWHmFUwyY=/fit-in/300x320/filters:strip_icc()/pic4930887.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "143741",
    "name": "BANG! The Dice Game",
    "yearPublished": 2013,
    "image": "https://cf.geekdo-images.com/BLTFau1Ue-gjX6geQdYrjQ__original/img/3CcRDvDttHpWLP6wc_jZHufTfl4=/0x0/filters:format(jpeg)/pic2909713.jpg",
    "thumbnail": "https://cf.geekdo-images.com/BLTFau1Ue-gjX6geQdYrjQ__previewthumb/img/w_mUaVxwnNkZKgkpLUV4U3R4NMY=/fit-in/300x320/filters:strip_icc()/pic2909713.jpg",
    "minPlayers": 3,
    "maxPlayers": 8,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "American West",
      "Bluffing",
      "Deduction",
      "Dice",
      "Fighting",
      "Party Game"
    ],
    "owners": [
      "Lavin",
      "Winoko"
    ]
  },
  {
    "id": "315",
    "name": "Bagh Chal",
    "yearPublished": 1000,
    "image": "https://cf.geekdo-images.com/HAHDwn-VmDwgM2gIYTrEGQ__original/img/U35Mn1JWnxQUgcMkSS4LOV12zUQ=/0x0/filters:format(jpeg)/pic9457619.jpg",
    "thumbnail": "https://cf.geekdo-images.com/HAHDwn-VmDwgM2gIYTrEGQ__previewthumb/img/dQkLqjKFM7kGA5MGOQA4wIs8vAY=/fit-in/300x320/filters:strip_icc()/pic9457619.jpg",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 20,
    "maxPlayTime": 20,
    "communityRating": 6.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "166658",
    "name": "Bakerspeed",
    "yearPublished": 2014,
    "image": "https://cf.geekdo-images.com/19jZKi5_lbrKrFAZoNhGQA__original/img/45QJB6PCkAxHKoCGTxZORAIkEaY=/0x0/filters:format(jpeg)/pic2268644.jpg",
    "thumbnail": "https://cf.geekdo-images.com/19jZKi5_lbrKrFAZoNhGQA__previewthumb/img/ODFXhesyWvxsB9eg4b6ln-v5108=/fit-in/300x320/filters:strip_icc()/pic2268644.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 4.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Dice",
      "Real-time"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "368341",
    "name": "Bako: Dig and Write",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/UU9h_U4A09QlnKjIe3mwFA__original/img/bLgS_bDimfmDjhxeZnKN0X3Gnp4=/0x0/filters:format(png)/pic7001862.png",
    "thumbnail": "https://cf.geekdo-images.com/UU9h_U4A09QlnKjIe3mwFA__previewthumb/img/SD6wvsKras2CEc9e6eqAep7qpdY=/fit-in/300x320/filters:strip_icc()/pic7001862.png",
    "minPlayers": 1,
    "maxPlayers": 99,
    "minPlayTime": 20,
    "maxPlayTime": 40,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Dice",
      "Prehistoric",
      "Print & Play"
    ],
    "owners": [
      "Sam"
    ]
  },
  {
    "id": "233956",
    "name": "Bali",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/YsKICppLcRYjAa3KKK9chQ__original/img/46M1fDb3thU9blk7hY7u5omdV8w=/0x0/filters:format(jpeg)/pic3714305.jpg",
    "thumbnail": "https://cf.geekdo-images.com/YsKICppLcRYjAa3KKK9chQ__previewthumb/img/MIUW9rNAItajkzW3otg_uEMpd4Q=/fit-in/300x320/filters:strip_icc()/pic3714305.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 6.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Economic"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "5716",
    "name": "Balloon Cup",
    "yearPublished": 2003,
    "image": "https://cf.geekdo-images.com/YHPPsc22emFVr-eXHPd_BA__original/img/Tgf9oZJzPw3kKM1lrVNvtjPx7kk=/0x0/filters:format(jpeg)/pic63292.jpg",
    "thumbnail": "https://cf.geekdo-images.com/YHPPsc22emFVr-eXHPd_BA__previewthumb/img/BdkUmf0iRTonmofHBZnwVLOYZCc=/fit-in/300x320/filters:strip_icc()/pic63292.jpg",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Aviation / Flight",
      "Card Game"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "351538",
    "name": "Bamboo",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/JPk8CpExdhywjxerrXWXBQ__original/img/FT_tdh1klaCfDfhx-6oSRqPsiqc=/0x0/filters:format(jpeg)/pic7141455.jpg",
    "thumbnail": "https://cf.geekdo-images.com/JPk8CpExdhywjxerrXWXBQ__previewthumb/img/KoOOv5hkS0H1GYaJuJJbv-tqHg0=/fit-in/300x320/filters:strip_icc()/pic7141455.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 90,
    "maxPlayTime": 110,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Fantasy",
      "Farming"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "338",
    "name": "Bargain Hunter",
    "yearPublished": 1998,
    "image": "https://cf.geekdo-images.com/8ivvc_2NjujMTmwT3eugeg__original/img/lJOEut-D4s8Q6sBjwSJaUnXyIPs=/0x0/filters:format(jpeg)/pic681363.jpg",
    "thumbnail": "https://cf.geekdo-images.com/8ivvc_2NjujMTmwT3eugeg__previewthumb/img/3kHHmj8azxVQHLfPBbWceFI5wT8=/fit-in/300x320/filters:strip_icc()/pic681363.jpg",
    "minPlayers": 3,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "415838",
    "name": "Battalion: War of the Ancients",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/i38Sbt0z4upJloTLK4mdYQ__original/img/snfBiS5nkvCv54lewaKceObcm1Q=/0x0/filters:format(jpeg)/pic8091755.jpg",
    "thumbnail": "https://cf.geekdo-images.com/i38Sbt0z4upJloTLK4mdYQ__previewthumb/img/r5VFbsyQqwUoT5LnSHo4WZDfTdk=/fit-in/300x320/filters:strip_icc()/pic8091755.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 20,
    "maxPlayTime": 45,
    "communityRating": 7.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Ancient",
      "Wargame"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "297985",
    "name": "Battle Line: Medieval",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/i2S4_8bOrSINBEdA95vgRg__original/img/dbHmpHQNSkflMmtR2T2jyUpTIRA=/0x0/filters:format(jpeg)/pic5102612.jpg",
    "thumbnail": "https://cf.geekdo-images.com/i2S4_8bOrSINBEdA95vgRg__previewthumb/img/reVas_KJJ4iMT-IslIfe_jlEDoM=/fit-in/300x320/filters:strip_icc()/pic5102612.jpg",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Medieval"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "54137",
    "name": "Battle Sheep",
    "yearPublished": 2010,
    "image": "https://cf.geekdo-images.com/CyRdRpZaIsCb4B8zfotI4Q__original/img/5FfCNbuFMYfXNoUKKAZkJugz-dE=/0x0/filters:format(jpeg)/pic1887253.jpg",
    "thumbnail": "https://cf.geekdo-images.com/CyRdRpZaIsCb4B8zfotI4Q__previewthumb/img/cS4lW9B-siHkhYXeWVMXJGoiRyY=/fit-in/300x320/filters:strip_icc()/pic1887253.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 6.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Animals"
    ],
    "owners": [
      "Noah",
      "Winoko"
    ]
  },
  {
    "id": "278305",
    "name": "Battlelands",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/teCqjDym7KUX3O2vCU1iuw__original/img/pCE4XU8YmCCvABm4V6JRSW4h8_o=/0x0/filters:format(jpeg)/pic4706005.jpg",
    "thumbnail": "https://cf.geekdo-images.com/teCqjDym7KUX3O2vCU1iuw__previewthumb/img/iQptzARg9uW7g2kTDbw0pATGzPs=/fit-in/300x320/filters:strip_icc()/pic4706005.jpg",
    "minPlayers": 3,
    "maxPlayers": 5,
    "minPlayTime": 30,
    "maxPlayTime": 60,
    "communityRating": 6.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals"
    ],
    "owners": [
      "Yos"
    ]
  },
  {
    "id": "37111",
    "name": "Battlestar Galactica: The Board Game",
    "yearPublished": 2008,
    "image": "https://cf.geekdo-images.com/5Q2w2rFJiFI_uV89KP6ECg__original/img/MYuRAKLRAGlIQTph2XKWjzqT7sQ=/0x0/filters:format(jpeg)/pic354500.jpg",
    "thumbnail": "https://cf.geekdo-images.com/5Q2w2rFJiFI_uV89KP6ECg__previewthumb/img/0ypf97Vwr1pOm4bmX9f-gvWK5W8=/fit-in/300x320/filters:strip_icc()/pic354500.jpg",
    "minPlayers": 3,
    "maxPlayers": 6,
    "minPlayTime": 120,
    "maxPlayTime": 180,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Bluffing",
      "Deduction",
      "Movies / TV / Radio theme",
      "Political",
      "Science Fiction",
      "Space Exploration",
      "Spies/Secret Agents"
    ],
    "owners": [
      "Wicak"
    ]
  },
  {
    "id": "362976",
    "name": "Beacon Patrol",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/9hDNHVLmorkaytg2ztLM6w__original/img/k5cnBMKBb94XWGhL0aEyYOlaWtQ=/0x0/filters:format(jpeg)/pic7439416.jpg",
    "thumbnail": "https://cf.geekdo-images.com/9hDNHVLmorkaytg2ztLM6w__previewthumb/img/SIKd9Cjd7cAp-m6XR6Euvq8m_KA=/fit-in/300x320/filters:strip_icc()/pic7439416.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Exploration",
      "Nautical"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "211534",
    "name": "Bears vs Babies",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/2BZROogBECvPPF2780wlvg__original/img/LAUIOIEPo54Qis-r8FDiE6kqqh4=/0x0/filters:format(jpeg)/pic5521191.jpg",
    "thumbnail": "https://cf.geekdo-images.com/2BZROogBECvPPF2780wlvg__previewthumb/img/REyo9rf1MuZT3OHwP-bvqthnjH0=/fit-in/300x320/filters:strip_icc()/pic5521191.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 15,
    "maxPlayTime": 20,
    "communityRating": 5.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Card Game",
      "Comic Book / Strip",
      "Humor"
    ],
    "owners": [
      "Noah"
    ]
  },
  {
    "id": "358504",
    "name": "Betrayal at House on the Hill: 3rd Edition",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/nLDGtbwdSC0eYKffjYzrnQ__original/img/KlTmf1wl3PsFlPtQek6BfjUOC4A=/0x0/filters:format(jpeg)/pic6917219.jpg",
    "thumbnail": "https://cf.geekdo-images.com/nLDGtbwdSC0eYKffjYzrnQ__previewthumb/img/Chiu1mqey1pFuTGrxPWReB4XaiM=/fit-in/300x320/filters:strip_icc()/pic6917219.jpg",
    "minPlayers": 3,
    "maxPlayers": 6,
    "minPlayTime": 60,
    "maxPlayTime": 60,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Exploration",
      "Horror",
      "Miniatures"
    ],
    "owners": [
      "Malik"
    ]
  },
  {
    "id": "34219",
    "name": "Biblios",
    "yearPublished": 2007,
    "image": "https://cf.geekdo-images.com/w9pHmbMbHEFYtuOUcWcruA__original/img/jOmzNb1JROlzeqEmCDScX_IkHVU=/0x0/filters:format(jpeg)/pic759154.jpg",
    "thumbnail": "https://cf.geekdo-images.com/w9pHmbMbHEFYtuOUcWcruA__previewthumb/img/eo0w8axaput645j1ErYTuykrzFw=/fit-in/300x320/filters:strip_icc()/pic759154.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Medieval",
      "Religious"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "380677",
    "name": "Biohack",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/E2AuzdG8J0AdSO8L_ZwOaQ__original/img/dnAZkH-RDSrfAt6VjgqrQNuH5DQ=/0x0/filters:format(png)/pic7356910.png",
    "thumbnail": "https://cf.geekdo-images.com/E2AuzdG8J0AdSO8L_ZwOaQ__previewthumb/img/824mswUtPxCiZDYPOvH9zoCFkxc=/fit-in/300x320/filters:strip_icc()/pic7356910.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 90,
    "communityRating": 7.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Mythology",
      "Science Fiction"
    ],
    "owners": [
      "Winoko",
      "Wicak"
    ]
  },
  {
    "id": "277927",
    "name": "Bites",
    "yearPublished": 2020,
    "image": "https://cf.geekdo-images.com/I8cU6zMT5z40Km3Nnv2iqg__original/img/0zYDSbfi4cAKRnDh9NrUUitCnts=/0x0/filters:format(jpeg)/pic7591344.jpg",
    "thumbnail": "https://cf.geekdo-images.com/I8cU6zMT5z40Km3Nnv2iqg__previewthumb/img/6reWOW5_ERTlpC5aPXX2m5AluPI=/fit-in/300x320/filters:strip_icc()/pic7591344.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 20,
    "maxPlayTime": 20,
    "communityRating": 7.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Animals"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "420805",
    "name": "Black Forest",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/zyc92pV4Mn2G6HCegMGPWQ__original/img/39E8tEi-2NbBcXmduY5XHF1GeBU=/0x0/filters:format(jpeg)/pic8194217.jpg",
    "thumbnail": "https://cf.geekdo-images.com/zyc92pV4Mn2G6HCegMGPWQ__previewthumb/img/BZWP6gi3xk4xvgPXHRnmyCuxJC8=/fit-in/300x320/filters:strip_icc()/pic8194217.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "City Building",
      "Economic",
      "Industry / Manufacturing",
      "Medieval"
    ],
    "owners": [
      "Dedi",
      "Aswin"
    ]
  },
  {
    "id": "262215",
    "name": "Blackout: Hong Kong",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/jOLEKfuTY4gLszR1h-0Bfw__original/img/MdeUWXhaqOaDwYULBIWER5vBKTA=/0x0/filters:format(jpeg)/pic4338675.jpg",
    "thumbnail": "https://cf.geekdo-images.com/jOLEKfuTY4gLszR1h-0Bfw__previewthumb/img/miMPKT3H77aZqT0ts3Lp1SZJfL0=/fit-in/300x320/filters:strip_icc()/pic4338675.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 75,
    "maxPlayTime": 150,
    "communityRating": 7.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Exploration"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "226592",
    "name": "Blackwood",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/yRJaahP2aUULsLSwVm98oA__original/img/hJYulntUPcyZYgJoxEoLSP3tB2w=/0x0/filters:format(jpeg)/pic3544199.jpg",
    "thumbnail": "https://cf.geekdo-images.com/yRJaahP2aUULsLSwVm98oA__previewthumb/img/ypsfZIRjNnRDh_BhH4re952V39w=/fit-in/300x320/filters:strip_icc()/pic3544199.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 60,
    "communityRating": 6.5,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Fantasy",
      "Medieval"
    ],
    "owners": [
      "Reinard"
    ]
  },
  {
    "id": "371973",
    "name": "Blind Business",
    "yearPublished": 2023,
    "image": "https://cf.geekdo-images.com/zSLyy6ueV3wNU5j8k3KCeA__original/img/YDmy2qWNqZvqtQ3Ws1sW-aN86xg=/0x0/filters:format(jpeg)/pic7382288.jpg",
    "thumbnail": "https://cf.geekdo-images.com/zSLyy6ueV3wNU5j8k3KCeA__previewthumb/img/Hwm1OmPUiGL7ZSD4lTkaHKqGfJ4=/fit-in/300x320/filters:strip_icc()/pic7382288.jpg",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 15,
    "maxPlayTime": 30,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Bluffing",
      "Card Game",
      "Negotiation"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "1197",
    "name": "Blink",
    "yearPublished": 1995,
    "image": "https://cf.geekdo-images.com/3dIGGmZpEj8ND0WwBWGtDw__original/img/6EifG7D8YEKnT65VGKfbyc6sSss=/0x0/filters:format(png)/pic8946171.png",
    "thumbnail": "https://cf.geekdo-images.com/3dIGGmZpEj8ND0WwBWGtDw__previewthumb/img/O4Tv8FTWqXu4Ot8PmZGTS8sXK2A=/fit-in/300x320/filters:strip_icc()/pic8946171.png",
    "minPlayers": 2,
    "maxPlayers": 3,
    "minPlayTime": 10,
    "maxPlayTime": 10,
    "communityRating": 5.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Action / Dexterity",
      "Card Game",
      "Children's Game",
      "Real-time"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "258210",
    "name": "Blitzkrieg!: World War Two in 20 Minutes",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/O03NSgVOl-FsbLiAg_GV1w__original/img/ZUTVxECQWoM6lGek5g6LTgj-ypE=/0x0/filters:format(jpeg)/pic4306846.jpg",
    "thumbnail": "https://cf.geekdo-images.com/O03NSgVOl-FsbLiAg_GV1w__previewthumb/img/F9fF8ddwcy0FN0IjHpMKD7gCouo=/fit-in/300x320/filters:strip_icc()/pic4306846.jpg",
    "minPlayers": 1,
    "maxPlayers": 2,
    "minPlayTime": 20,
    "maxPlayTime": 45,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Wargame",
      "World War II"
    ],
    "owners": [
      "Aswin"
    ]
  },
  {
    "id": "328624",
    "name": "Block Ness",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/sfkdzzjxCkuH2e2bCEnazA__original/img/AoMEfrvB2lmeK2XH70jIB50WNJA=/0x0/filters:format(png)/pic6029823.png",
    "thumbnail": "https://cf.geekdo-images.com/sfkdzzjxCkuH2e2bCEnazA__previewthumb/img/-rX6nP9vT3ntJZX0HgAj9mlMCl0=/fit-in/300x320/filters:strip_icc()/pic6029823.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 20,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Animals",
      "Fantasy"
    ],
    "owners": [
      "Yos"
    ]
  },
  {
    "id": "2453",
    "name": "Blokus",
    "yearPublished": 2000,
    "image": "https://cf.geekdo-images.com/96YA5wUJDxtPkmPxemr5Qg__original/img/sdX6o0TZpXjsDMw071k2P80wpYw=/0x0/filters:format(jpeg)/pic2197702.jpg",
    "thumbnail": "https://cf.geekdo-images.com/96YA5wUJDxtPkmPxemr5Qg__previewthumb/img/a6t32G9Whtz3WIKIGpnKITRMkBQ=/fit-in/300x320/filters:strip_icc()/pic2197702.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Territory Building"
    ],
    "owners": [
      "Daniel",
      "Poetra",
      "Winoko"
    ]
  },
  {
    "id": "16395",
    "name": "Blokus Duo",
    "yearPublished": 2005,
    "image": "https://cf.geekdo-images.com/pn92DM-FlWMRWusB0eP7vQ__original/img/fS5gAR00MprmNdhliAflDD8Wjv4=/0x0/filters:format(jpeg)/pic1086904.jpg",
    "thumbnail": "https://cf.geekdo-images.com/pn92DM-FlWMRWusB0eP7vQ__previewthumb/img/wyVTxjpywalCLaD_sIMOgWwgRZk=/fit-in/300x320/filters:strip_icc()/pic1086904.jpg",
    "minPlayers": 2,
    "maxPlayers": 2,
    "minPlayTime": 10,
    "maxPlayTime": 20,
    "communityRating": 6.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Territory Building"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "21550",
    "name": "Blokus Trigon",
    "yearPublished": 2006,
    "image": "https://cf.geekdo-images.com/aPTEkOgzqLH4v-kY4M0zXQ__original/img/n5kvQb3ZR8Ga_s1_0imfrNZHHyw=/0x0/filters:format(jpeg)/pic5412064.jpg",
    "thumbnail": "https://cf.geekdo-images.com/aPTEkOgzqLH4v-kY4M0zXQ__previewthumb/img/ue7FLbod32XLwjlus1c96W2q1s4=/fit-in/300x320/filters:strip_icc()/pic5412064.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 20,
    "maxPlayTime": 20,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy",
      "Territory Building"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "170216",
    "name": "Blood Rage",
    "yearPublished": 2015,
    "image": "https://cf.geekdo-images.com/HkZSJfQnZ3EpS214xtuplg__original/img/Myy6IPDJDzLoPdXrPXVZcddBQoQ=/0x0/filters:format(jpeg)/pic2439223.jpg",
    "thumbnail": "https://cf.geekdo-images.com/HkZSJfQnZ3EpS214xtuplg__previewthumb/img/FIhMI0SWGTgyZyZbMzvNN423ln0=/fit-in/300x320/filters:strip_icc()/pic2439223.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 90,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy",
      "Fighting",
      "Miniatures",
      "Mythology"
    ],
    "owners": [
      "Poetra",
      "Dzikri"
    ]
  },
  {
    "id": "195856",
    "name": "Bloodborne: The Card Game",
    "yearPublished": 2016,
    "image": "https://cf.geekdo-images.com/zczRMJvEEGhqLGwxxOQQuw__original/img/QhIAddgMu-_s-pJnQTruIOnj9fg=/0x0/filters:format(jpeg)/pic3297526.jpg",
    "thumbnail": "https://cf.geekdo-images.com/zczRMJvEEGhqLGwxxOQQuw__previewthumb/img/QEAkNx6_Cbk8ZGiW0NcrBbQRf-4=/fit-in/300x320/filters:strip_icc()/pic3297526.jpg",
    "minPlayers": 3,
    "maxPlayers": 5,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Fantasy",
      "Horror",
      "Video Game Theme"
    ],
    "owners": [
      "Lavin"
    ]
  },
  {
    "id": "244331",
    "name": "Blue Lagoon",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/wFggDB9IbU47-drR4GUQBw__original/img/L4ZGFJOUs0huPAZWNYa8Ol_ra_A=/0x0/filters:format(png)/pic4122624.png",
    "thumbnail": "https://cf.geekdo-images.com/wFggDB9IbU47-drR4GUQBw__previewthumb/img/wF4s2dMHPtlDCqfMkBnohamo1Gg=/fit-in/300x320/filters:strip_icc()/pic4122624.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Abstract Strategy"
    ],
    "owners": [
      "Daniel",
      "Aswin"
    ]
  },
  {
    "id": "21882",
    "name": "Blue Moon City",
    "yearPublished": 2006,
    "image": "https://cf.geekdo-images.com/1MRXcnaF8VqPaeIS6cEUDQ__original/img/lEJBqf8knsJjfPOGXtLa7Dc71bA=/0x0/filters:format(jpeg)/pic4757841.jpg",
    "thumbnail": "https://cf.geekdo-images.com/1MRXcnaF8VqPaeIS6cEUDQ__previewthumb/img/cgHSpbWdoyRzHsq4hnBXLQjWAr8=/fit-in/300x320/filters:strip_icc()/pic4757841.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 50,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "City Building",
      "Fantasy"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "11",
    "name": "Bohnanza",
    "yearPublished": 1997,
    "image": "https://cf.geekdo-images.com/8SADtu_4zBH_UJrCo935Iw__original/img/RNuAr2CDbxE3XzeJVkxj4Df3eVM=/0x0/filters:format(jpeg)/pic6348964.jpg",
    "thumbnail": "https://cf.geekdo-images.com/8SADtu_4zBH_UJrCo935Iw__previewthumb/img/a0NWSB3UZ_3iTZb4gWfa3l9n-mA=/fit-in/300x320/filters:strip_icc()/pic6348964.jpg",
    "minPlayers": 2,
    "maxPlayers": 7,
    "minPlayTime": 45,
    "maxPlayTime": 45,
    "communityRating": 7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Farming",
      "Negotiation"
    ],
    "owners": [
      "Daniel",
      "Malik"
    ]
  },
  {
    "id": "413246",
    "name": "Bomb Busters",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/HpGXIlt5i6T-0jbiQRReOg__original/img/2uApg8IOYjNVSzbUIwJUa-Z8eL8=/0x0/filters:format(png)/pic8303080.png",
    "thumbnail": "https://cf.geekdo-images.com/HpGXIlt5i6T-0jbiQRReOg__previewthumb/img/s_X4Pt2lxWuhhBqgiYy0m51Rqug=/fit-in/300x320/filters:strip_icc()/pic8303080.png",
    "minPlayers": 2,
    "maxPlayers": 5,
    "minPlayTime": 30,
    "maxPlayTime": 30,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Deduction",
      "Spies / Secret Agents"
    ],
    "owners": [
      "Malik"
    ]
  },
  {
    "id": "300369",
    "name": "Boomerang: USA",
    "yearPublished": 2020,
    "image": "https://cf.geekdo-images.com/9Etoc4dPb4-HeYLqaUtgbg__original/img/3kFhmTcSe23KBEFHQ0AdFl_bAW8=/0x0/filters:format(png)/pic5227837.png",
    "thumbnail": "https://cf.geekdo-images.com/9Etoc4dPb4-HeYLqaUtgbg__previewthumb/img/X_bXmt7nLnLmLsBUS3TMIqro0u4=/fit-in/300x320/filters:strip_icc()/pic5227837.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 30,
    "communityRating": 6.9,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "Travel"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "343905",
    "name": "Boonlake",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/xRcKQXVz-mDxz-32Jf7gCg__original/img/2HWmLnNrR9Kbz-9NAOiOUk6t-qk=/0x0/filters:format(jpeg)/pic6313605.jpg",
    "thumbnail": "https://cf.geekdo-images.com/xRcKQXVz-mDxz-32Jf7gCg__previewthumb/img/L2v0fBqRuHVwK65oVqR1bwjxTx8=/fit-in/300x320/filters:strip_icc()/pic6313605.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 80,
    "maxPlayTime": 160,
    "communityRating": 7.8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "American West",
      "Civilization",
      "Economic",
      "Exploration",
      "Farming",
      "Industry / Manufacturing",
      "Territory Building",
      "Travel"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "12477",
    "name": "Bootleggers",
    "yearPublished": 2004,
    "image": "https://cf.geekdo-images.com/tvLJz97IYY6mvmvIM2P1NQ__original/img/kD_0fTeBYBpXTxbxX9hw9-k6ft8=/0x0/filters:format(jpeg)/pic51819.jpg",
    "thumbnail": "https://cf.geekdo-images.com/tvLJz97IYY6mvmvIM2P1NQ__previewthumb/img/UBUg-l6ID_3jShdGF3_5sg-wxug=/fit-in/300x320/filters:strip_icc()/pic51819.jpg",
    "minPlayers": 3,
    "maxPlayers": 6,
    "minPlayTime": 90,
    "maxPlayTime": 90,
    "communityRating": 6.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Industry / Manufacturing",
      "Mafia",
      "Negotiation",
      "Transportation"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "127060",
    "name": "Bora Bora",
    "yearPublished": 2013,
    "image": "https://cf.geekdo-images.com/9YEjZIVdWVcUVWC7o8aKsQ__original/img/FmxZfRUytUU35lwbNkTetKJT6YM=/0x0/filters:format(jpeg)/pic1542342.jpg",
    "thumbnail": "https://cf.geekdo-images.com/9YEjZIVdWVcUVWC7o8aKsQ__previewthumb/img/bV2bR5ACq5H8jMA2dvoQJ57S7nA=/fit-in/300x320/filters:strip_icc()/pic1542342.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 7.6,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Dice"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "380837",
    "name": "Botany",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/keC0oy0nbpewpRTdcte42Q__original/img/QNK35DZ__DvatgNqOkXKdZF5QM0=/0x0/filters:format(png)/pic7361181.png",
    "thumbnail": "https://cf.geekdo-images.com/keC0oy0nbpewpRTdcte42Q__previewthumb/img/_J_1Bg9oB6wk45seIdXUKA5u_5Q=/fit-in/300x320/filters:strip_icc()/pic7361181.png",
    "minPlayers": 1,
    "maxPlayers": 5,
    "minPlayTime": 45,
    "maxPlayTime": 90,
    "communityRating": 7.1,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Adventure",
      "Educational",
      "Humor",
      "Travel"
    ],
    "owners": [
      "Dedi"
    ]
  },
  {
    "id": "28720",
    "name": "Brass",
    "yearPublished": 2007,
    "image": "https://cf.geekdo-images.com/tHVtPzu82mBpeQbbZkV6EA__original/img/3ffdJj5Pz6HQrg09Kh8ecTen-TY=/0x0/filters:format(jpeg)/pic3469216.jpg",
    "thumbnail": "https://cf.geekdo-images.com/tHVtPzu82mBpeQbbZkV6EA__previewthumb/img/i4D6lHHUy4zRfL7dUViWNAnvxgk=/fit-in/300x320/filters:strip_icc()/pic3469216.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 8.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Industry / Manufacturing",
      "Post-Napoleonic",
      "Transportation"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "224517",
    "name": "Brass: Birmingham",
    "yearPublished": 2018,
    "image": "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxH41Y6_ROoePAilPNEhXnzO8=/0x0/filters:format(jpeg)/pic3490053.jpg",
    "thumbnail": "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__previewthumb/img/Y9apAdg80y0-RV1Oxze6ZwzZe18=/fit-in/300x320/filters:strip_icc()/pic3490053.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 120,
    "communityRating": 8.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Economic",
      "Industry / Manufacturing",
      "Post-Napoleonic",
      "Transportation"
    ],
    "owners": [
      "Aswin"
    ]
  },
  {
    "id": "332386",
    "name": "Brew",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/8eN5t1p4ncee-eVN9NswDA__original/img/Hhv8kruqZZH1vv5W7gR7QXNZ_KM=/0x0/filters:format(png)/pic6007253.png",
    "thumbnail": "https://cf.geekdo-images.com/8eN5t1p4ncee-eVN9NswDA__previewthumb/img/-h0XPtSveEXcY-4bhUMnRid8YfI=/fit-in/300x320/filters:strip_icc()/pic6007253.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 90,
    "communityRating": 7.2,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fantasy"
    ],
    "owners": [
      "Noah",
      "Poetra",
      "Yofiandhy",
      "Winoko"
    ]
  },
  {
    "id": "136888",
    "name": "Bruges",
    "yearPublished": 2013,
    "image": "https://cf.geekdo-images.com/A8JeebUT3mu4zUmYs9clDQ__original/img/v5d03Jz4di-I6S6C1iihj6JEeoY=/0x0/filters:format(jpeg)/pic1652004.jpg",
    "thumbnail": "https://cf.geekdo-images.com/A8JeebUT3mu4zUmYs9clDQ__previewthumb/img/bQTYSJiFUgJhwRJxOPB6hyyLocQ=/fit-in/300x320/filters:strip_icc()/pic1652004.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 60,
    "maxPlayTime": 60,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game",
      "City Building",
      "Economic",
      "Renaissance"
    ],
    "owners": [
      "Daniel"
    ]
  },
  {
    "id": "275913",
    "name": "Bruxelles 1897",
    "yearPublished": 2019,
    "image": "https://cf.geekdo-images.com/epYZrJ9M2vTl6ITcl28eQg__original/img/nmNX-gMBA0bL0VgXQOrucQF56tQ=/0x0/filters:format(jpeg)/pic4830437.jpg",
    "thumbnail": "https://cf.geekdo-images.com/epYZrJ9M2vTl6ITcl28eQg__previewthumb/img/JQ9dgAjplbcZog8RU0cA2Bnv5cY=/fit-in/300x320/filters:strip_icc()/pic4830437.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 40,
    "maxPlayTime": 60,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "343844",
    "name": "Bullet★",
    "yearPublished": 2022,
    "image": "https://cf.geekdo-images.com/2CkIttJMYQ4zVwdM4PeRGA__original/img/qkzmh4m5UVZqztGDRVumajcTD4k=/0x0/filters:format(png)/pic6314116.png",
    "thumbnail": "https://cf.geekdo-images.com/2CkIttJMYQ4zVwdM4PeRGA__previewthumb/img/n05nRKG7yOuHuJv_9rMiy7blQiA=/fit-in/300x320/filters:strip_icc()/pic6314116.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 8,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fighting",
      "Puzzle",
      "Real-time",
      "Science Fiction"
    ],
    "owners": [
      "Winoko"
    ]
  },
  {
    "id": "307305",
    "name": "Bullet♥︎",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/315gnIdET7dlQ_fASt8p0w__original/img/X2MDGNIMouqDtC6617rzlxW5LDw=/0x0/filters:format(jpeg)/pic6007944.jpg",
    "thumbnail": "https://cf.geekdo-images.com/315gnIdET7dlQ_fASt8p0w__previewthumb/img/uGqhCFEdMb1eIXRub-_lxtwMbT8=/fit-in/300x320/filters:strip_icc()/pic6007944.jpg",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 10,
    "maxPlayTime": 20,
    "communityRating": 7.7,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Fighting",
      "Puzzle",
      "Real-time",
      "Science Fiction"
    ],
    "owners": [
      "Yos",
      "Winoko"
    ]
  },
  {
    "id": "286537",
    "name": "Burgle Bros 2: The Casino Capers",
    "yearPublished": 2021,
    "image": "https://cf.geekdo-images.com/YNcSJhDM_g-2av0pzNs4wQ__original/img/G87808ARUrKMTSecrfiZRUYNtyU=/0x0/filters:format(png)/pic6087472.png",
    "thumbnail": "https://cf.geekdo-images.com/YNcSJhDM_g-2av0pzNs4wQ__previewthumb/img/RNwdSumRkMVItFo0NNQ9E5cnwh8=/fit-in/300x320/filters:strip_icc()/pic6087472.png",
    "minPlayers": 1,
    "maxPlayers": 4,
    "minPlayTime": 45,
    "maxPlayTime": 70,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Exploration",
      "Maze",
      "Spies/Secret Agents"
    ],
    "owners": [
      "Malik"
    ]
  },
  {
    "id": "418581",
    "name": "Bus & Stop",
    "yearPublished": 2024,
    "image": "https://cf.geekdo-images.com/x43rioxfA1oKiMtgrreagg__original/img/rqnX_dnjcrZk4NGaCUtGcABssVU=/0x0/filters:format(png)/pic8132820.png",
    "thumbnail": "https://cf.geekdo-images.com/x43rioxfA1oKiMtgrreagg__previewthumb/img/TlVlXo6OJZjfRbvrYwmvlNZmmJk=/fit-in/300x320/filters:strip_icc()/pic8132820.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 15,
    "maxPlayTime": 15,
    "communityRating": 7.4,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Card Game"
    ],
    "owners": [
      "Yofiandhy",
      "Dedi"
    ]
  },
  {
    "id": "219513",
    "name": "Bärenpark",
    "yearPublished": 2017,
    "image": "https://cf.geekdo-images.com/9JC16l1EMwmJkpbjaUBkpw__original/img/H14LeRRtvcOajZ1Z1_pRYu_rSTM=/0x0/filters:format(jpeg)/pic3486218.jpg",
    "thumbnail": "https://cf.geekdo-images.com/9JC16l1EMwmJkpbjaUBkpw__previewthumb/img/sDJMD2zJBUHhiBkqdi0HSoyq__0=/fit-in/300x320/filters:strip_icc()/pic3486218.jpg",
    "minPlayers": 2,
    "maxPlayers": 4,
    "minPlayTime": 30,
    "maxPlayTime": 45,
    "communityRating": 7.3,
    "userRating": null,
    "bggRank": null,
    "numPlays": 0,
    "categories": [
      "Animals",
      "Puzzle"
    ],
    "owners": [
      "Winoko"
    ]
  }
]
