import { readFileSync, writeFileSync } from 'fs'

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0 Safari/537.36'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const raw = JSON.parse(readFileSync('scripts/scraped-raw.json', 'utf8'))
const rows = raw.games.filter((g) => g.id && g.name)
console.log(`Enriching ${rows.length} games...`)

const parseRating = (s) => {
  if (!s || s === 'N/A') return null
  const n = parseFloat(s)
  return Number.isFinite(n) ? n : null
}
const parseYear = (s) => {
  const m = (s || '').match(/(\d{4})/)
  return m ? parseInt(m[1], 10) : null
}

const games = []
for (let idx = 0; idx < rows.length; idx++) {
  const row = rows[idx]
  let detail = {}
  try {
    const res = await fetch(
      `https://api.geekdo.com/api/geekitems?objectid=${row.id}&objecttype=thing`,
      { headers: { 'User-Agent': UA, Accept: 'application/json' } }
    )
    if (res.ok) {
      const json = await res.json()
      detail = json.item || {}
    } else {
      console.warn(`  [${idx + 1}/${rows.length}] ${row.name}: HTTP ${res.status}`)
    }
  } catch (e) {
    console.warn(`  [${idx + 1}/${rows.length}] ${row.name}: ${e.message}`)
  }

  const thumb = detail.images?.thumb || detail.imageurl || ''
  const image = detail.images?.original || detail.images?.square200 || thumb

  games.push({
    id: String(row.id),
    name: row.name,
    yearPublished: parseYear(row.yearRaw) ?? (detail.yearpublished ? parseInt(detail.yearpublished, 10) : null),
    thumbnail: thumb,
    image,
    minPlayers: detail.minplayers ? parseInt(detail.minplayers, 10) : 1,
    maxPlayers: detail.maxplayers ? parseInt(detail.maxplayers, 10) : 1,
    minPlayTime: detail.minplaytime ? parseInt(detail.minplaytime, 10) : 0,
    maxPlayTime: detail.maxplaytime ? parseInt(detail.maxplaytime, 10) : 0,
    userRating: parseRating(row.userRatingRaw),
    communityRating: parseRating(row.communityRatingRaw) ?? 0,
    bggRank: null,
    numPlays: 0,
  })

  console.log(`  [${idx + 1}/${rows.length}] ${row.name} ✓`)
  await sleep(250) // be polite to the API
}

const fileContent = `import { BoardGame } from './types'

// Real collection for BGG user "Deedeen" (Sholahuddin Al Ayubi)
// Scraped ${games.length} owned games from BoardGameGeek.
// Generated by scripts/build-deedeen.mjs — do not edit by hand.
export const DEEDEEN_COLLECTION: BoardGame[] = ${JSON.stringify(games, null, 2)}
`

writeFileSync('lib/deedeen-collection.ts', fileContent)
console.log(`\nWrote lib/deedeen-collection.ts with ${games.length} games`)
