// One-time (re-runnable) enrichment: fetch weight/mechanics/designers from BGG's
// `thing` API for every game id in lib/community.ts and write lib/game-meta.ts.
// Requires BGG_API_TOKEN in .env.local. Usage: node scripts/enrich-meta.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { XMLParser } from 'fast-xml-parser'

const env = readFileSync(new URL('../.env.local', import.meta.url), 'utf8')
const token = env.match(/^BGG_API_TOKEN=(.+)$/m)?.[1]?.trim()
if (!token) {
  console.error('BGG_API_TOKEN not found in .env.local')
  process.exit(1)
}

// Collect unique game ids from the static community library…
const community = readFileSync(new URL('../lib/community.ts', import.meta.url), 'utf8')
const idSet = new Set([...community.matchAll(/"id":\s*"(\d+)"/g)].map((m) => m[1]))

// …plus any game ids that members have synced into member_collections (via REST).
const sbUrl = env.match(/^NEXT_PUBLIC_SUPABASE_URL=(.+)$/m)?.[1]?.trim()
const sbKey = env.match(/^NEXT_PUBLIC_SUPABASE_(?:PUBLISHABLE_KEY|ANON_KEY)=(.+)$/m)?.[1]?.trim()
if (sbUrl && sbKey) {
  try {
    const res = await fetch(`${sbUrl}/rest/v1/member_collections?select=game_id`, {
      headers: { apikey: sbKey, Authorization: `Bearer ${sbKey}` },
    })
    if (res.ok) {
      const rows = await res.json()
      for (const r of rows) if (/^\d+$/.test(String(r.game_id))) idSet.add(String(r.game_id))
      console.log(`+ ${rows.length} member-collection rows scanned`)
    }
  } catch (e) {
    console.warn('could not read member_collections:', e.message)
  }
}
const ids = [...idSet]
console.log(`enriching ${ids.length} games…`)

const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '@_',
  isArray: (n) => n === 'item' || n === 'link',
})

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const meta = {}

for (let i = 0; i < ids.length; i += 20) {
  const batch = ids.slice(i, i + 20)
  let xml = ''
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch(`https://boardgamegeek.com/xmlapi2/thing?id=${batch.join(',')}&stats=1`, {
      headers: { Authorization: `Bearer ${token}`, 'User-Agent': 'BBGC/1.0' },
    })
    if (res.status === 200) { xml = await res.text(); break }
    if (res.status === 202) { await sleep(2000); continue }
    console.error(`batch ${i / 20 + 1}: HTTP ${res.status}`)
    break
  }
  if (!xml) continue
  const data = parser.parse(xml)
  const items = data.items?.item ?? []
  for (const it of items) {
    const id = String(it['@_id'])
    const weight = parseFloat(it.statistics?.ratings?.averageweight?.['@_value'] ?? '0') || null
    const links = it.link ?? []
    const mechanics = links.filter((l) => l['@_type'] === 'boardgamemechanic').map((l) => l['@_value'])
    const designers = links.filter((l) => l['@_type'] === 'boardgamedesigner').map((l) => l['@_value'])
    meta[id] = { weight, mechanics, designers }
  }
  console.log(`  ${Math.min(i + 20, ids.length)}/${ids.length}`)
  await sleep(800)
}

const body = `// Auto-generated by scripts/enrich-meta.mjs — do not edit by hand.
// BGG \`thing\` enrichment: complexity weight, mechanics, designers, keyed by game id.
export interface GameMeta {
  weight: number | null
  mechanics: string[]
  designers: string[]
}

export const GAME_META: Record<string, GameMeta> = ${JSON.stringify(meta, null, 2)}
`
writeFileSync(new URL('../lib/game-meta.ts', import.meta.url), body)
console.log(`wrote lib/game-meta.ts with ${Object.keys(meta).length} entries`)
